{
 "title": "FHIR server performance",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "runid",
    "label": "RunID",
    "query": {
     "query": "label_values(k6_http_reqs_total, runid)"
    }
   },
   {
    "name": "branch",
    "label": "Branch",
    "query": {
     "query": "label_values(k6_http_reqs_total,branch)"
    }
   },
   {
    "name": "commit",
    "label": "Commit",
    "query": {
     "query": "label_values(k6_http_reqs_total,commit)"
    }
   },
   {
    "name": "server",
    "label": "FHIR server",
    "query": {
     "query": "label_values(k6_http_reqs_total,fhirimpl)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CRUD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "Requests per second. (Higher is better)",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs_total{runid=~\"$runid\", commit=~\"$commit\", branch=~\"$branch\", fhirimpl=~\"$server\", scenario=\"crud\"}[$__rate_interval])) by (fhirimpl, scenario)",
     "legendFormat": "{{fhirimpl}}"
    }
   ]
  },
  {
   "title": "Latensy",
   "type": "timeseries",
   "description": "P99 in milliseconds. (Higher is better)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "k6_http_req_duration_p99{runid=~\"$runid\", commit=~\"$commit\", branch=~\"$branch\", fhirimpl=~\"$server\", scenario=\"crud\"}",
     "legendFormat": "{{fhirimpl}}{{group}}"
    }
   ]
  },
  { "title": "Bulk import", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "Requests per second. (Higher is better)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(k6_http_reqs_total{runid=~\"$runid\", fhirimpl=~\"$server\", scenario=\"import\"}[$__rate_interval])) by (fhirimpl, scenario)",
     "legendFormat": "{{fhirimpl}}"
    }
   ]
  },
  {
   "title": "Imported resource",
   "type": "timeseries",
   "description": "Total count of all resources across all bundles per second (Higher is better)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "res/s" } },
   "targets": [
    {
     "expr": "rate(k6_bundle_size_total{fhirimpl=~\"$server\"}[$__rate_interval])",
     "legendFormat": "{{fhirimpl}}"
    }
   ]
  },
  { "title": "Resource utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{runid=~\"$runid\", commit=~\"$commit\", branch=~\"$branch\", name=~\".+\", name!~\"perf-k6.*\"}[$__rate_interval])) by (name) *100",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{ name=~\".+\", runid=\"golden\", container_label_com_docker_compose_project_working_dir=\"/home/aitem/golden\"}[$__rate_interval])) by (container_label_com_docker_compose_service) * 100",
     "legendFormat": "golden-{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{runid=~\"$runid\", commit=~\"$commit\", branch=~\"$branch\", name=~\".+\", name!~\"perf-k6.*\"}) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(container_memory_rss{runid=\"golden\", container_label_com_docker_compose_project_working_dir=\"/home/aitem/golden\"}) by (container_label_com_docker_compose_service)",
     "legendFormat": "golden-{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  { "title": "Search", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(irate(k6_http_reqs_total{runid=~\"$runid\", fhirimpl=~\"$server\", scenario=\"search\"}[$__rate_interval])) by (fhirimpl, scenario)",
     "legendFormat": "{{fhirimpl}} / {{scenario}}"
    }
   ]
  },
  {
   "title": "P99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "k6_http_req_duration_p99{fhirimpl=~\"$server\", scenario=\"search\"}",
     "legendFormat": "{{method}} {{fhirimpl}}{{group}}"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(irate(k6_http_reqs_total{runid=~\"$runid\", commit=~\"$commit\", branch=~\"$branch\", fhirimpl=~\"$server\"}[$__rate_interval])) by (fhirimpl, scenario)",
     "legendFormat": "{{fhirimpl}} / {{scenario}}"
    }
   ]
  },
  {
   "title": "AVG RPS",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs_total{runid=~\"$runid\", fhirimpl=~\"$server\"}[$__rate_interval])) by (fhirimpl, scenario)",
     "legendFormat": "{{fhirimpl}} / {{scenario}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Database size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{runid=~\"$runid\", commit=~\"$commit\", branch=~\"$branch\", datname=~\"aidbox|hapi|medplum\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit {runid=~\"$runid\", commit=~\"$commit\", branch=~\"$branch\", datname=~\"aidbox|hapi|medplum\"} [$__rate_interval])) by (datname)\n",
     "legendFormat": "Commit - {{datname}}"
    },
    {
     "expr": "sum(irate(pg_stat_database_xact_rollback {runid=~\"$runid\", commit=~\"$commit\", branch=~\"$branch\", datname=~\"aidbox|hapi|medplum\"} [$__rate_interval])) by (datname)\n",
     "legendFormat": "RollBack - {{datname}}"
    }
   ]
  },
  { "title": "Population", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Import resources",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "sum(rate(app_import_resource_total) [$__rate_interval]) by (server, resourceType) > 0",
     "legendFormat": "{{server}}/{{resourceType}}"
    }
   ]
  },
  {
   "title": "Import resources",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 77 },
   "targets": [
    {
     "expr": "sum(rate(app_import_resource_total) [$__rate_interval]) by (server) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SQL Server (Microsoft FHIR datastore)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 }
  },
  {
   "title": "SQL Server database size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(mssql_database_filesize{runid=~\"$runid\", commit=~\"$commit\", branch=~\"$branch\", database=\"FHIR\"}) by (database) * 1024",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "SQL Server TPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(mssql_transactions{runid=~\"$runid\", commit=~\"$commit\", branch=~\"$branch\", database=\"FHIR\"}[$__rate_interval])) by (database)",
     "legendFormat": "{{database}}"
    }
   ]
  }
 ]
}